import Head from "next/head";

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();

  return {
    props: {
      todos: data,
    },
  };
}

export default function Home({todos}) {
  return (
    <>
      <Head>
        <title>SSR - Server Side Rendering</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>This Json is an example of the Server Side Rendering through props</h1>
      <h2>Taken from jsonplaceholder.typicode.com/</h2>
      
      <br></br>

      {todos?.length === 0 ? (
        <div>Loading...</div>
      ) : (
        todos?.map((todo) => (
          <div key={todo.id}>
            <p>
              {todo.id}: {todo.title}
            </p>
          </div>
        ))
      )}

      
    </>
  );
}
